export const ErrorCode = {
  CHAT_GENERATION_FAILED: "CHAT_GENERATION_FAILED",
  INVALID_MODEL: "INVALID_MODEL",
  MODEL_NOT_FOUND: "MODEL_NOT_FOUND",
  RATE_LIMITED: "RATE_LIMITED",
  UNAUTHORIZED: "UNAUTHORIZED",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
} as const;

export type ErrorCode =
  (typeof ErrorCode)[keyof typeof ErrorCode];